### ISSUE TITLE
Mixing Product Category and Event Category

### ISSUE THREAD

**Issue by nordjac** [segment-integrations/analytics.js-integration-google-analytics#41]
When you set a Product category (example calling Product View) it also applies to the Event category.

Example:
```javascript
analytics.track('Product Viewed', {
  name: 'Compton T-Shirt',
  sku: '9bdd2',
  price: 44.00,
  brand: 'Compton',
  category: 'T-Shirts',
  quantity: 1,
  currency: 'USD'
});
```

The expected analytics Event category is '[EnhancedEcommerce](https://github.com/segment-integrations/analytics.js-integration-google-analytics/blob/master/lib/index.js#L578)' but now both Event category and Product 1 category have value 'T-Shirt'. 
![image](https://cloud.githubusercontent.com/assets/1086680/22221091/c047dc86-e1b1-11e6-9fa9-2d0dd10dc672.png)

Is there any way to separate the two categories?

**Comment by ladanazita** [comment]
Hey @nordjac !

Thanks for your patience here. 

We looked into this internally, and you are correct that given the way we have things [spec'd](https://segment.com/docs/spec/ecommerce/v2/), we do not have an idea for an "event level" category on singular product events. We map the event and product category to be the same value for product viewed events, for example `products.category` spec’d should be `products.$.category`.

The current expected behavior is, when sending product level events, there is no higher event category within the scope of that event. Events with multiple products nested in have an event level category such as [Product List Viewed](https://segment.com/docs/spec/ecommerce/v2/#product-list-viewed), we have `properties.category` and `products.category` spec'd. 

While the behavior you are requesting is reasonable, we do not see this as a strong argument to restructure our e-commerce spec in order to fix this. If you have a compelling use case why this is problematic, we are happy to continue looking into a resolution here.
